"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";

export default function SummaryPage() {
  const { meetingId } = useParams();
  const router = useRouter();
  const [summary, setSummary] = useState("");
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem(`summary-${meetingId}`);
    if (stored) {
      setSummary(stored);
      setLoading(false);
    } else {
      router.push("/dashboard/meetings");
    }
  }, [meetingId]);

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <p className="text-gray-500">Loading summary...</p>
      </div>
    );
  }

  // Parse summary into sections by looking for ** or numbered lines
  const lines = summary.split("\n").filter((l) => l.trim());

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-2xl font-bold text-black">Meeting Summary</h1>
            <p className="text-gray-500 mt-1 text-sm">
              AI-generated summary of your meeting
            </p>
          </div>
          <Link
            href="/dashboard/meetings"
            className="text-sm border border-gray-200 text-gray-600 px-4 py-2 rounded-lg hover:bg-gray-50 transition-colors"
          >
            ← Back to Meetings
          </Link>
        </div>

        {/* Summary card */}
        <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-8 mb-4">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-green-100 rounded-xl flex items-center justify-center">
                <span className="text-xl">📋</span>
              </div>
              <div>
                <h2 className="font-semibold text-black">Summary</h2>
                <p className="text-xs text-gray-400">Generated by AI</p>
              </div>
            </div>
            <button
              onClick={handleCopy}
              className={`text-xs px-3 py-1.5 rounded-lg border transition-colors ${
                copied
                  ? "bg-green-50 border-green-200 text-green-600"
                  : "border-gray-200 text-gray-600 hover:bg-gray-50"
              }`}
            >
              {copied ? "✓ Copied!" : "Copy"}
            </button>
          </div>

          <div className="space-y-3">
            {lines.map((line, i) => {
              // Bold headers (lines with ** or all caps or ending with :)
              const isHeader =
                line.startsWith("**") ||
                line.startsWith("#") ||
                (line.endsWith(":") && line.length < 50);

              const cleanLine = line
                .replace(/\*\*/g, "")
                .replace(/^#+\s*/, "")
                .trim();

              if (!cleanLine) return null;

              if (isHeader) {
                return (
                  <h3
                    key={i}
                    className="font-semibold text-black text-sm mt-4 first:mt-0"
                  >
                    {cleanLine}
                  </h3>
                );
              }

              // Bullet points
              if (line.startsWith("-") || line.startsWith("•")) {
                return (
                  <div key={i} className="flex items-start gap-2 text-sm text-gray-700">
                    <span className="text-gray-400 mt-0.5">•</span>
                    <span>{cleanLine.replace(/^[-•]\s*/, "")}</span>
                  </div>
                );
              }

              // Numbered list
              if (/^\d+\./.test(line)) {
                return (
                  <div key={i} className="flex items-start gap-2 text-sm text-gray-700">
                    <span className="text-gray-400 font-medium w-4 flex-shrink-0">
                      {line.match(/^\d+/)?.[0]}.
                    </span>
                    <span>{cleanLine.replace(/^\d+\.\s*/, "")}</span>
                  </div>
                );
              }

              return (
                <p key={i} className="text-sm text-gray-700 leading-relaxed">
                  {cleanLine}
                </p>
              );
            })}
          </div>
        </div>

        {/* Action buttons */}
        <div className="grid grid-cols-2 gap-3">
          <Link
            href="/dashboard/meetings"
            className="bg-black text-white py-3 rounded-xl text-sm font-medium text-center hover:bg-gray-800 transition-colors"
          >
            + New Meeting
          </Link>
          <button
            onClick={handleCopy}
            className="border border-gray-200 text-gray-700 py-3 rounded-xl text-sm font-medium hover:bg-gray-50 transition-colors"
          >
            {copied ? "✓ Copied!" : "Copy Summary"}
          </button>
        </div>
      </div>
    </div>
  );
}